### ISSUE TITLE
the link of pretrained agent has expired.

### ISSUE THREAD

**Issue by Hebanxi4n** [zgoddard3/jsbsim-gym#1]
Thank you very much for your work, which has been very helpful to my learning. But I encountered some problems while using it. My personal computer was unable to train it, and the server in the lab also broke down for some reasons. Therefore, I wanted to use the model you provided, but I found that the link has expired. Can you please give me a link? Thank you very much!

**Comment by zgoddard3** [comment]
Link is updated. This one shouldn't expire.
