### ISSUE TITLE
Required Libraries Versions

### ISSUE THREAD

**Issue by kryC1** [zgoddard3/jsbsim-gym#3]
Hi @zgoddard3, could you please specify the versions of the required libraries? There are some conflicts between the latest versions.

**Comment by ydyvip** [comment]
> Hi @zgoddard3, could you please specify the versions of the required libraries? There are some conflicts between the latest versions.

I was trying hard to make the list.:)
ale_py==0.7.4
gym==0.21.0
imageio==2.34.2
imageio-ffmpeg
JSBSim==1.2.0
moderngl==5.10.0
numpy==1.24.4
pygame==2.6.0
stable_baselines3==1.6.0
torch==2.3.1
scipy
matplotlib
setuptools==65.5.0
wheel==0.38.4
shimmy==0.2.1

**Comment by zgoddard3** [comment]
The requirements file has been updated and tested with Python 3.9.7.
